# **TUGAS NUMPY**

---

Nama: Christama Ezra Yudianto

NIM: 245150307111009

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [25]:
import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 4, 5, 4, 5])

n = len(A)
mean_A = np.mean(A)
mean_B = np.mean(B)

slope = np.sum((A - mean_A) * (B - mean_B)) / np.sum((A - mean_A) ** 2)
intercept = mean_B - slope * mean_A

print(f"Slope: {slope}, Intercept: {intercept}")

X_new = 6
predicted_Y = slope * X_new + intercept
print(f"Prediksi nilai untuk X={X_new}: {predicted_Y}")


Slope: 0.6, Intercept: 2.2
Prediksi nilai untuk X=6: 5.8


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [26]:

A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 4, 5, 4, 5])

degree = 2  
coefficients = np.polyfit(A, B, degree)

print(f"Koefisien Polinomial: {coefficients}")

X_new = 6
predicted_Y = np.polyval(coefficients, X_new)
print(f"Prediksi nilai untuk X={X_new}: {predicted_Y:.2f}")

Koefisien Polinomial: [-0.28571429  2.31428571  0.2       ]
Prediksi nilai untuk X=6: 3.80


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [27]:
random_array = np.random.randint(0, 100, (10, 10, 10))

min_value = np.min(random_array)
max_value = np.max(random_array)
print(f"Elemen Minimum: {min_value}")
print(f"Elemen Maksimum: {max_value}")

Elemen Minimum: 0
Elemen Maksimum: 99


In [28]:
mean_value = np.mean(random_array)
median_value = np.median(random_array)
print(f"Rata-rata: {mean_value}")
print(f"Median: {median_value}")


Rata-rata: 48.724
Median: 48.0


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [29]:
arr1 = np.full((10, 10), '8', dtype=str)  
arr1[0, :] = arr1[-1, :] = '5'  
arr1[:, 0] = arr1[:, -1] = '5'  
print("Array 10x10 dengan bingkai 5:")
print(arr1)

Array 10x10 dengan bingkai 5:
[['5' '5' '5' '5' '5' '5' '5' '5' '5' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '8' '8' '8' '8' '8' '8' '8' '8' '5']
 ['5' '5' '5' '5' '5' '5' '5' '5' '5' '5']]


In [30]:
arr2 = np.zeros((8, 8), dtype=int)  
arr2[1::2, ::2] = 1  
arr2[::2, 1::2] = 1  
print("\nArray 8x8 pola catur:")
print(arr2)


Array 8x8 pola catur:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
arr3 = np.zeros((15, 15), dtype=object)  
for i in range(15):
    for j in range(15):
        num = i * 15 + j 
        divisors = ''
        if num % 2 == 0:
            divisors += '2'
        if num % 3 == 0:
            divisors += '3'
        if num % 5 == 0:
            divisors += '5'
        arr3[i, j] = divisors if divisors else '0'
print("\nArray 15x15 dengan aturan pembagian:")
print(arr3)



Array 15x15 dengan aturan pembagian:
[['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2']
 ['35' '2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0']
 ['235' '0' '2' '

## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [32]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Tanggal hari ini:", today)
print("Tanggal kemarin:", yesterday)
print("Tanggal besok:", tomorrow)

Tanggal hari ini: 2025-02-21
Tanggal kemarin: 2025-02-20
Tanggal besok: 2025-02-22


In [33]:
may_2020 = np.arange('2020-05', '2020-06', dtype='datetime64[D]')
print("Hari di bulan Mei 2020: ", may_2020)


Hari di bulan Mei 2020:  ['2020-05-01' '2020-05-02' '2020-05-03' '2020-05-04' '2020-05-05'
 '2020-05-06' '2020-05-07' '2020-05-08' '2020-05-09' '2020-05-10'
 '2020-05-11' '2020-05-12' '2020-05-13' '2020-05-14' '2020-05-15'
 '2020-05-16' '2020-05-17' '2020-05-18' '2020-05-19' '2020-05-20'
 '2020-05-21' '2020-05-22' '2020-05-23' '2020-05-24' '2020-05-25'
 '2020-05-26' '2020-05-27' '2020-05-28' '2020-05-29' '2020-05-30'
 '2020-05-31']


## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [34]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
A[3, 1]


200

In [35]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

primes = A[np.vectorize(is_prime)(A)]
print(primes.reshape(-1, 1))


[]


In [36]:
np.concatenate((A[0, :], A[1:-1, -1], A[-1, ::-1], A[1:-1, 0]))

array([ 10,  20,  30,  40,  50,  60, 120, 180, 240, 300, 290, 280, 270,
       260, 250,  70, 130, 190])

In [37]:
A[:, 1::2]

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180],
       [200, 220, 240],
       [260, 280, 300]])

In [38]:
A[:4, 2:4]

array([[ 30,  40],
       [ 90, 100],
       [150, 160],
       [210, 220]])

## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [39]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
